version: '3'

services:

  autoservice-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=autoservice
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - backend

  autoservice-main:
    build: .
    depends_on:
      - autoservice-mysql
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend: